### ISSUE TITLE
Cannot Ollie.with(context).init()

### ISSUE THREAD

**Issue by razgrizbw** [pardom/Ollie#40]
01-14 18:25:58.495  10589-10608/com.android.raz.gathering E/Ollie﹕ Failed to initialize.
    java.lang.ClassNotFoundException: ollie.AdapterHolderImpl
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:308)
            at java.lang.Class.forName(Class.java:272)
            at ollie.Ollie.init(Ollie.java:133)
            at ollie.Ollie$Builder.init(Ollie.java:298)

should I create new class AdapterHolderImpl????

**Comment by pardom** [comment]
Did you include the compiler dependency?
```groovy
provided 'com.michaelpardo:ollie-compiler:0.3.1'
```

**Comment by razgrizbw** [comment]
app/build.gradle:
```
dependencies {
        compile 'com.michaelpardo:ollie:0.3.1'
        provided 'com.michaelpardo:ollie-compiler:0.3.1'
   }
```

do I need to add any repositories in project build.gradle?

**Comment by pardom** [comment]
The compiler should generate AdapterHolderImpl or fail to compile. Are there any build errors. Can you post information that will let me reproduce this? e.g. your model.

**Comment by svenofix** [comment]
Jumping in to hopefully add some more info as I'm also getting the same issue.

I created a brand new project for this. Nothing special in the build.gradle settings.

    android {
        compileSdkVersion 21
        buildToolsVersion "21.1.2"

        defaultConfig {
            minSdkVersion 15
            targetSdkVersion 21
            ...
        }
    }
    dependencies {
        ...
        compile 'com.michaelpardo:ollie:0.3.1'
        provided 'com.michaelpardo:ollie-compiler:0.3.1'
    }

I'm also initializing Ollie within the onCreate() method of my MainActivity. I have no models defined, the only code I've added is the code to init Ollie. As far as I'm aware, this should be ok. Additionally, I'm using Android Studio 1.0.2 for Linux with a Nexus 5 as my target device.

There are no build errors, no gradle warnings or errors. Everything seems to compile.

One question, shouldn't I be able view the generated AdapterHolderImpl class within the build folder of the app? With Dagger 2 at least, I am able to view the classes it generates.

**Comment by razgrizbw** [comment]
I find the issue maybe cause by android-apt
When I use "androidannotation" it seems does not run the compiler to make AdapterHolderImpl.java file
so there is no error and cannot init

**Comment by pardom** [comment]
Annotation processing is done using the java compiler, so that's not the issue. The problem is that Ollie expects you will have a model and generates this class only when the annotations are found. Is there a reason you don't have a model?

**Comment by svenofix** [comment]
Ah, I just figured it would run regardless ;)
But still, even with a model defined, AdapterHolderImpl isn't being generated/found.

    @Table("item")
    public class Item extends Model {
        @Column("name")
        public String name;
    }

**Comment by pardom** [comment]
Are you using the Eclipse compiler or javac?

**Comment by svenofix** [comment]
Most definitely javac.

**Comment by svenofix** [comment]
Ok. I figured out why it wasn't working for me. When I made sure I had a model defined, I was in another small test application that was using android-apt.

    apply plugin: 'com.neenbedankt.android-apt'

Removing said plugin from the build.gradle, I was able to get Ollie to work.

I should make sure in future that when testing at work, the project I'm using is indeed clean and set up properly. Sorry for the misinformation!

**Comment by razgrizbw** [comment]
But I use androidannotation which need android-apt
Can this be fix in future?

**Comment by ciprig** [comment]
For me it's only working with apply plugin: 'com.neenbedankt.android-apt'
If I don't add the lib and use only   provided 'com.michaelpardo:ollie-compiler:0.3.1' it will not generate any class.

**Comment by raymondlukanta** [comment]
@razgrizbw have you tried to use

```
compile 'com.michaelpardo:ollie:0.3.1'
    apt 'com.michaelpardo:ollie-compiler:0.3.1'
```

?

**Comment by laochiv** [comment]
I would like to chime in here as well. I am attempting to combine the usage of [AndroidAnnotations](https://github.com/excilys/androidannotations) and am failing. When I use the lines

```
compile 'com.michaelpardo:ollie:0.3.1'
provided 'com.michaelpardo:ollie-compiler:0.3.1'
```

The project builds just fine however I get the ClassNotFoundException.

I tried the change @rymdemon suggested however that resulted in AndroidAnnotations apt command not being run which results in many build errors (I tried changing the order of these two and it didn't help).

Is there a special way to call apt when you have two projects? I've googled and cannot find one. 

If it is helpful, here is basically my build.gradle (just edited out my application names and stuff)
    buildscript {
        repositories {
            maven { url 'https://maven.fabric.io/public' }
        }

```
    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url 'https://maven.fabric.io/public' }
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'android-apt'
def AndAnnVersion = '3.1'

dependencies {
    compile fileTree(dir: 'Libraries/jars', include: '*.jar')
    apt "org.androidannotations:androidannotations:$AndAnnVersion"
    compile "org.androidannotations:androidannotations-api:$AndAnnVersion"

    compile 'com.android.support:appcompat-v7:21.0.+'
    compile 'com.android.support:cardview-v7:21.0.+'
    compile 'com.android.support:recyclerview-v7:21.0.+'

    compile 'com.getbase:floatingactionbutton:1.9.0'
    compile project(':Libraries:ViewPagerTransforms')

    provided 'com.michaelpardo:ollie-compiler:0.3.1'
    compile 'com.michaelpardo:ollie:0.3.1'

    compile('com.crashlytics.sdk.android:crashlytics:2.2.3@aar') {
        transitive = true;
    }
}

apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile

        // If you're using Android NBS flavors you should use the following line instead of hard-coded packageName
        resourcePackageName android.defaultConfig.applicationId

        // Used to enable @SupposeUiThread and @SupposeBackground
        threadControl true
    }
}

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        applicationId "application"
    }

    productFlavors {
        a {
            applicationId "application.flavor1"
        }
        b {
            applicationId "application.flavor2"
        }
    }
}
```

**Comment by raymondlukanta** [comment]
@laochiv, do you use `int, boolean, double` instead of `Integer, Boolean, Double` in your model?
In order to make Ollie works, you have to use the object (wrapper class), not the primitive type.

**Comment by laochiv** [comment]
@rymdemon I was using a `boolean` in one of my models. I will test what happens when I get some free time. Thanks for the insight

**Comment by laochiv** [comment]
@rymdemon That worked great! Once I figured out how to do an Adapter and that the Column member variables are required to be public it works like a charm. Thanks for your help!

EDIT: Note this is in addition to the `apt 'com.michaelpardo:ollie-compiler:0.3.1'` change
