### ISSUE TITLE
TypeAdapterElement NPE during compiliation

### ISSUE THREAD

**Issue by jbarr21** [pardom/Ollie#46]
I have a pretty basic Model (see below), but I am using gradle-retrolambda if that could affect it.

```
@Table("Measurements")
public class MeasurementModel extends Model {
    @Column("date")
	public long date;
    @Column("time")
    public String time;
	@Column("weight")
	public double weight;
    @Column("fat")
    public double fat;

    @Column("trend")
    public double trend;
```

```
Caused by: java.lang.NullPointerException
	at ollie.internal.codegen.Registry.getTypeAdapterElement(Registry.java:83)
	at ollie.internal.codegen.element.ColumnElement.<init>(ColumnElement.java:73)
	at ollie.internal.codegen.step.ModelAdapterStep.addColumnElements(ModelAdapterStep.java:89)
	at ollie.internal.codegen.step.ModelAdapterStep.process(ModelAdapterStep.java:65)
	at ollie.internal.codegen.OllieProcessor.process(OllieProcessor.java:76)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

**Comment by jbarr21** [comment]
I removed the retrolambda plugin, and still get the same error above. I'm compiling with Java 7 and here is my init call in the app's onCreate()

```
Ollie.with(this)
                .setName(DATABASE_NAME)
                .setVersion(DATABASE_VERSION)
                .setLogLevel(LogLevel.FULL)
                .init();
```

**Comment by lauw** [comment]
Check out https://github.com/pardom/Ollie/issues/41.
Basically you can only use the wrapper classes of the primitive types, and not the primitive types themselves.

So 'Double' instead of 'double'

**Comment by jbarr21** [comment]
Thanks @lauw. Coming from ActiveAndroid, this is an interesting design decision. Looking forward to the wiki =]
