### ISSUE TITLE
Creating a TypeAdapter for List<String> 

### ISSUE THREAD

**Issue by T-Spoon** [pardom/Ollie#57]
Is it possible to create a TypeAdapters for Lists?  Below is what I'm trying at the moment.

```
@Table("articles")
public class Article extends Model {
    @Column("tags")
    private List<String> tags;
}

public class StringListTypeAdapter extends TypeAdapter<List<String>, String> {
    @Override
    public String serialize(List<String> value) {
        return StringUtil.join(value, "|||");
    }

    @Override
    public List<String> deserialize(String value) {
        return Arrays.asList(value.split("|||"));
    }
}
```

The compile fails with the following stack trace:

```
Caused by: java.lang.NullPointerException
    at ollie.internal.codegen.element.TypeAdapterElement.getDeserializedQualifiedName(TypeAdapterElement.java:69)
    at ollie.internal.codegen.Registry.addTypeAdapterModel(Registry.java:91)
    at ollie.internal.codegen.step.TypeAdapterStep.process(TypeAdapterStep.java:60)
    at ollie.internal.codegen.OllieProcessor.process(OllieProcessor.java:76)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    ... 32 more
```

If it's not possible to do this, is there a good workaround that anyone uses to support Lists in their model?

**Comment by kaeawc** [comment]
At the end of the day, you're using sqlite: http://stackoverflow.com/questions/5299267/how-to-create-enum-type-in-sqlite

If you don't need to query this table by that columns values I would just serialize the list as text in the `tags` field. If you do, then I would either create other tables to allow a many-to-many mapping: `Article` - `ArticleTags` - `Tags`. If you need to query it _and_ have low read latency, I would do both and make sure the application code always updated both the `ArticleTags` records and the `tags` field in `Article` when there was a change so that you could quickly read the tags field.
