### ISSUE TITLE
Error:Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.NullPointerException

### ISSUE THREAD

**Issue by developer--** [pardom/Ollie#77]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.leavingstone.aversi"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

```
dataBinding {
    enabled = true
}

buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
lintOptions {
    disable 'InvalidPackage'
}
```

}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/core-3.2.1-sources.jar')
    compile files('libs/core-3.2.1.jar')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:design:23.2.0'
    compile 'com.specyci:residemenu:1.6+'
    compile 'eu.the4thfloor.volley:com.android.volley:2015.05.28'
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.android.support:percent:23.2.0'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.michaelpardo:ollie:0.3.1'
    provided 'com.michaelpardo:ollie-compiler:0.3.1'

}
apply plugin: 'com.google.gms.google-services'

**Comment by hangnadi** [comment]
Same problem.
Here some additional info for anyone could help.

thanks

`Caused by: java.lang.NullPointerException
        at ollie.internal.codegen.Registry.getTypeAdapterElement(Registry.java:83)
        at ollie.internal.codegen.element.ColumnElement.<init>(ColumnElement.java:73)
        at ollie.internal.codegen.step.ModelAdapterStep.addColumnElements(ModelAdapterStep.java:89)
        at ollie.internal.codegen.step.ModelAdapterStep.process(ModelAdapterStep.java:65)
        at ollie.internal.codegen.OllieProcessor.process(OllieProcessor.java:76)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        ... 79 more
`

**Comment by altairmizuchi** [comment]
Same problem here

**Comment by aneeskhadija** [comment]
Hello sir... 
yesterday  i have upgrade android studio 2.2.2... but i run the application then the bug like this appeared

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> java.io.FileNotFoundException: G:\OsYar\Osyar\app\libs\universal-image-loader-1.9.0.jar (The system cannot find the file specified)
